# Generated by Django 3.0.8 on 2020-09-04 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_job_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='description',
        ),
    ]
